use game_udb_00;
ALTER TABLE `player_00`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_10`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_20`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_30`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_40`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_50`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_60`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_70`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_80`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_90`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_01;
ALTER TABLE `player_01`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_11`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_21`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_31`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_41`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_51`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_61`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_71`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_81`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_91`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_02;
ALTER TABLE `player_02`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_12`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_22`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_32`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_42`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_52`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_62`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_72`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_82`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_92`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_03;
ALTER TABLE `player_03`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_13`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_23`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_33`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_43`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_53`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_63`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_73`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_83`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_93`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_04;
ALTER TABLE `player_04`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_14`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_24`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_34`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_44`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_54`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_64`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_74`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_84`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_94`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_05;
ALTER TABLE `player_05`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_15`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_25`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_35`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_45`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_55`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_65`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_75`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_85`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_95`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_06;
ALTER TABLE `player_06`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_16`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_26`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_36`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_46`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_56`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_66`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_76`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_86`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_96`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_07;
ALTER TABLE `player_07`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_17`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_27`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_37`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_47`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_57`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_67`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_77`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_87`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_97`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_08;
ALTER TABLE `player_08`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_18`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_28`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_38`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_48`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_58`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_68`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_78`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_88`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_98`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_09;
ALTER TABLE `player_09`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_19`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_29`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_39`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_49`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_59`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_69`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_79`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_89`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_99`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_00;
ALTER TABLE `player_00`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_10`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_20`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_30`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_40`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_50`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_60`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_70`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_80`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_90`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_01;
ALTER TABLE `player_01`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_11`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_21`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_31`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_41`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_51`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_61`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_71`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_81`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_91`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_02;
ALTER TABLE `player_02`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_12`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_22`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_32`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_42`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_52`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_62`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_72`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_82`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_92`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_03;
ALTER TABLE `player_03`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_13`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_23`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_33`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_43`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_53`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_63`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_73`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_83`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_93`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_04;
ALTER TABLE `player_04`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_14`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_24`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_34`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_44`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_54`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_64`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_74`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_84`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_94`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_05;
ALTER TABLE `player_05`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_15`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_25`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_35`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_45`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_55`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_65`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_75`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_85`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_95`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_06;
ALTER TABLE `player_06`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_16`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_26`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_36`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_46`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_56`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_66`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_76`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_86`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_96`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_07;
ALTER TABLE `player_07`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_17`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_27`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_37`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_47`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_57`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_67`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_77`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_87`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_97`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_08;
ALTER TABLE `player_08`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_18`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_28`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_38`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_48`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_58`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_68`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_78`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_88`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_98`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
use game_udb_09;
ALTER TABLE `player_09`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_19`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_29`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_39`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_49`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_59`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_69`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_79`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_89`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
ALTER TABLE `player_99`
MODIFY COLUMN `uid` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '角色ID' FIRST;
